# Generated by Django 2.2.6 on 2019-10-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='interface',
            field=models.CharField(choices=[('field', 'Текстовое поле')], max_length=30),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.CharField(choices=[('int', 'Числовой'), ('text', 'Текстовый')], default='int', max_length=30),
        ),
    ]
