# Generated by Django 2.2.6 on 2019-10-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191022_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='interface',
            field=models.CharField(choices=[('field', 'Текстовое поле')], default='field', max_length=30, verbose_name='Поле в опроснике'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя параметра'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='params',
            field=models.TextField(null=True, verbose_name='Конфигураци поля опросника'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.CharField(choices=[('int', 'Числовой'), ('text', 'Текстовый')], default='int', max_length=30, verbose_name='Тип параметра'),
        ),
    ]
