# Generated by Django 2.2.6 on 2019-10-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191022_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
    ]
