# Generated by Django 2.2.6 on 2019-10-22 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='patient',
        ),
        migrations.AddField(
            model_name='measurement',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Имя опросника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='patients',
            field=models.ManyToManyField(to='polls.Patient', verbose_name='Пациенты'),
        ),
        migrations.AddField(
            model_name='rule',
            name='patients',
            field=models.ManyToManyField(to='polls.Patient', verbose_name='Пациенты'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='parameters',
            field=models.ManyToManyField(to='polls.Parameter', verbose_name='Параметры'),
        ),
    ]
