# Generated by Django 2.2.6 on 2019-11-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191022_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Имя правила'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.CharField(choices=[('int', 'Целое число'), ('float', 'Десятичное число'), ('string', 'Строка'), ('text', 'Строка')], default='int', max_length=30, verbose_name='Тип параметра'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='days',
            field=models.TextField(verbose_name='Расписание'),
        ),
    ]
