# Generated by Django 2.2.6 on 2019-11-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20191105_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='patients',
        ),
        migrations.AddField(
            model_name='patient',
            name='polls',
            field=models.ManyToManyField(to='polls.Poll', verbose_name='Опросники'),
        ),
        migrations.AddField(
            model_name='patient',
            name='rules',
            field=models.ManyToManyField(to='polls.Rule', verbose_name='Правила'),
        ),
    ]
